name: my_first_workflow

on:
  push:
    branches:
      - main

jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: greeting
        run: echo "Hello Stranger, Welcome to my world"
  job_two:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - name: goodbye
        run: echo "Thank you for tunning in. Goodbye! mwah!"
